export const GET_WORK_ORDERS_BEGIN = "GET_WORK_ORDERS_BEGIN";
export const GET_WORK_ORDERS_SUCCESS = "GET_WORK_ORDERS_SUCCESS";
export const GET_WORK_ORDERS_FAILURE = "GET_WORK_ORDERS_FAILURE";

export const GET_WORK_ORDER_BEGIN = "GET_WORK_ORDER_BEGIN";
export const GET_WORK_ORDER_SUCCESS = "GET_WORK_ORDER_SUCCESS";
export const GET_WORK_ORDER_FAILURE = "GET_WORK_ORDER_FAILURE";

export const GET_WORK_ORDER_STREAM_BEGIN = "GET_WORK_ORDER_STREAM_BEGIN";
export const GET_WORK_ORDER_STREAM_SUCCESS = "GET_WORK_ORDER_STREAM_SUCCESS";
export const GET_WORK_ORDER_STREAM_FAILURE = "GET_WORK_ORDER_STREAM_FAILURE";

export const GET_WORK_ORDER_DISCUSSION_BEGIN = "GET_WORK_ORDER_DISCUSSION_BEGIN";
export const GET_WORK_ORDER_DISCUSSION_SUCCESS = "GET_WORK_ORDER_DISCUSSION_SUCCESS";
export const GET_WORK_ORDER_DISCUSSION_FAILURE = "GET_WORK_ORDER_DISCUSSION_FAILURE";

export const GET_WORK_ORDER_FILES_BEGIN = "GET_WORK_ORDER_FILES_BEGIN";
export const GET_WORK_ORDER_FILES_SUCCESS = "GET_WORK_ORDER_FILES_SUCCESS";
export const GET_WORK_ORDER_FILES_FAILURE = "GET_WORK_ORDER_FILES_FAILURE";