export const GET_SERVICES_BEGIN = "GET_SERVICES_BEGIN";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";

export const GET_SERVICES_OPTIONS_BEGIN = "GET_SERVICES_OPTIONS_BEGIN";
export const GET_SERVICES_OPTIONS_SUCCESS = "GET_SERVICES_OPTIONS_SUCCESS";
export const GET_SERVICES_OPTIONS_FAILURE = "GET_SERVICES_OPTIONS_FAILURE";
